config/routes.rb
Rails.application.routes.draw do
  resources :movies
  get '/movies/:id/same_director', to: 'movies#same_director', as: 'same_director'
end

app/models/movie.rb
class Movie < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController

  def show
    id = params[:id] # retrieve movie ID from URI route
    @movie = Movie.find(id) # look up movie by unique ID
    # will render app/views/movies/show.<extension> by default
  end

  def same_director
    @movie = Movie.find(params[:id])
    @same_movies = Movie.where(director: @movie.director).to_a
    @same_movies.each { |m|
      if m.id == @movie.id
        @same_movies.delete(m)
      end
    }
    if @same_movies.length == 0
      flash[:notice] = "#{@movie.title} has no director info"     
      redirect_to movies_path
    end
  end

  def index
    @redirect = false
    # rating logic
    if params[:ratings] # clicked on params
      @selected = params[:ratings].keys
      session[:selected] = @selected
      @movies = []
      @selected.each { |s| 
        Movie.where(rating: s).each { |z| 
          @movies.push z
        }
      }
      @movies = @movies
      @ratings = @selected
    elsif session[:selected] != nil # clicked on sort
      @movies = []
      session[:selected].each { |s| 
        Movie.where(rating: s).each { |z| 
          @movies.push z
        }
      }
      @movies = @movies
      @ratings = session[:selected]
      @redirect = true
    else # first time logging in
      @movies = Movie.all
      @ratings = ["G", "R", "PG-13", "PG"]
    end

    # sorting logic
    @session = nil
    @all_ratings = Movie.all.map {|movie| movie.rating}.uniq
    if params[:title]
      @movies = @movies.sort_by {|movie| movie.title}
      session[:sort] = "title"
      @session = :title
    elsif params[:release]
      @movies = @movies.sort_by {|movie| movie.release_date}
      session[:sort] = "release"
      @session = :release
    elsif session[:sort]
      if session[:sort] == "title"
        @movies = @movies.sort_by {|movie| movie.title}
        @redirect = true
        @session = :title
      elsif session[:sort] == "release"
        @movies = @movies.sort_by {|movie| movie.release_date}
        @redirect = true
        @session = :release
      else
        session[:sort] = "none"
        @session = :none
      end
    else # first time login
      @session = :none
    end

    if @redirect
      #redirect 
      @rating_hash = {}
      @ratings.each { |r|
        @rating_hash[r] = 1
      }
      redirect_to movies_path(:ratings => @rating_hash, @session => 'sorted')
    end

  end

  def new
    # default: render 'new' template
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update_attributes!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  private
    def movie_params
      params.require(:movie).permit(:title, :rating, :description, :release_date, :director)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.haml
!!! 5
%html
  %head
    %title Rotten Potatoes!
    = stylesheet_link_tag 'application'
    / # = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    %h1.title Rotten Potatoes!
    #main
      - if flash[:notice]
        #notice.message= flash[:notice]
      - elsif flash[:warning]
        #warning.message= flash[:warning]

      = yield

app/views/movies/edit.html.haml
-# edit.html.haml using partial

%h1 Edit Existing Movie

= form_tag movie_path(@movie), :method => :put do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Update Movie Info'

app/views/movies/index.html.haml
-#  This file is app/views/movies/index.html.haml

= form_tag movies_path(:foo => 'bar'), :method => :get, :id => "ratings_form" do
  Include: 
  - @all_ratings.each do |rating|
    = rating
    = check_box_tag "ratings[#{rating}]", 1, !!(@ratings.include? rating), :id => "ratings_#{rating}"
  = submit_tag 'Refresh', :id => "ratings_submit"

= form_tag 

%h1 All Movies

%table#movies
  %thead
    %tr
      - if params[:release]
        %th= link_to "Movie Title", movies_path(:title => 'sorted'), :id => "title_header"
        %th Rating
        %th Director
        %th{:class => 'hilite'} 
          =link_to "Release Date", movies_path(:release => 'sorted'), :id => "release_date_header"
        %th More Info  
      - elsif params[:title]
        %th{:class => 'hilite'} 
          = link_to "Movie Title", movies_path(:title => 'sorted'), :id => "title_header"
        %th Rating
        %th Director
        %th= link_to "Release Date", movies_path(:release => 'sorted'), :id => "release_date_header"
        %th More Info  
      - else
        %th= link_to "Movie Title", movies_path(:title => 'sorted'), :id => "title_header"
        %th Rating
        %th Director
        %th= link_to "Release Date", movies_path(:release => 'sorted'), :id => "release_date_header"
        %th More Info
  %tbody
    - @movies.each do |movie|
      %tr
        %td= movie.title 
        %td= movie.rating
        %td= movie.director
        %td= movie.release_date
        %td= link_to "More about #{movie.title}", movie_path(movie)

= link_to 'Add new movie', new_movie_path

app/views/movies/new.html.haml
%h1 Create New Movie

= form_tag movies_path do

  = label :movie, :title, 'Title'
  = text_field :movie, 'title'

  = label :movie, :director, 'Director'
  = text_field :movie, 'director'

  = label :movie, :rating, 'Rating'
  = select :movie, :rating, ['G','PG','PG-13','R','NC-17']

  = label :movie, :release_date, 'Released On'
  = date_select :movie, :release_date

  = submit_tag 'Save Changes'

app/views/movies/same_director.html.haml
-# in app/views/movies/same_director.html.haml

%h2 Same director movies as #{@movie.title}

%ul#details
  - @same_movies.each do |movie|
    %li
      = movie.title

= link_to 'Back to movie list', movies_path

app/views/movies/show.html.haml
-# in app/views/movies/show.html.haml

%h2 Details about #{@movie.title}

%ul#details
  %li
    Rating:
    = @movie.rating
  %li
    Director:
    = @movie.director
  %li
    Released on:
    = @movie.release_date.strftime("%B %d, %Y")

%h3 Description:

%p#description= @movie.description

= link_to 'Edit', edit_movie_path(@movie)
= button_to 'Delete', movie_path(@movie), :method => :delete, :confirm => 'Are you sure?'
= link_to 'Back to movie list', movies_path
= link_to 'Find Movies With Same Director', same_director_path(@movie)